const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  await prisma.salary.createMany({
    data: [
      {
        company: "google",
        role: "Software Engineer",
        level: "L3",
        location: "Bangalore",
        experience_years: 1,
        base_salary: 2200000,
        bonus: 300000,
        stock: 500000,
        total_compensation: 3000000,
        confidence_score: 0.9,
      },
      {
        company: "google",
        role: "Software Engineer",
        level: "L4",
        location: "Bangalore",
        experience_years: 3,
        base_salary: 3500000,
        bonus: 600000,
        stock: 1200000,
        total_compensation: 5300000,
        confidence_score: 0.9,
      },
      {
        company: "google",
        role: "Software Engineer",
        level: "L5",
        location: "Bangalore",
        experience_years: 6,
        base_salary: 5000000,
        bonus: 1000000,
        stock: 2500000,
        total_compensation: 8500000,
        confidence_score: 0.9,
      },
      {
        company: "microsoft",
        role: "Software Engineer",
        level: "L4",
        location: "Hyderabad",
        experience_years: 3,
        base_salary: 2800000,
        bonus: 400000,
        stock: 900000,
        total_compensation: 4100000,
        confidence_score: 0.9,
      },
      {
        company: "microsoft",
        role: "Software Engineer",
        level: "L5",
        location: "Hyderabad",
        experience_years: 6,
        base_salary: 4200000,
        bonus: 800000,
        stock: 2000000,
        total_compensation: 7000000,
        confidence_score: 0.9,
      },
      {
        company: "amazon",
        role: "Software Engineer",
        level: "L4",
        location: "Bangalore",
        experience_years: 2,
        base_salary: 2400000,
        bonus: 150000,
        stock: 1500000,
        total_compensation: 4050000,
        confidence_score: 0.9,
      },
      {
        company: "amazon",
        role: "Software Engineer",
        level: "L5",
        location: "Bangalore",
        experience_years: 5,
        base_salary: 3600000,
        bonus: 200000,
        stock: 2800000,
        total_compensation: 6600000,
        confidence_score: 0.9,
      },
      {
        company: "meta",
        role: "Software Engineer",
        level: "L4",
        location: "Bangalore",
        experience_years: 3,
        base_salary: 3800000,
        bonus: 700000,
        stock: 1800000,
        total_compensation: 6300000,
        confidence_score: 0.9,
      },
      {
        company: "meta",
        role: "Software Engineer",
        level: "L5",
        location: "Bangalore",
        experience_years: 6,
        base_salary: 5500000,
        bonus: 1100000,
        stock: 3500000,
        total_compensation: 10100000,
        confidence_score: 0.9,
      },
      {
        company: "flipkart",
        role: "Software Engineer",
        level: "L3",
        location: "Bangalore",
        experience_years: 1,
        base_salary: 1600000,
        bonus: 150000,
        stock: 200000,
        total_compensation: 1950000,
        confidence_score: 0.9,
      },
      {
        company: "flipkart",
        role: "Software Engineer",
        level: "L4",
        location: "Bangalore",
        experience_years: 3,
        base_salary: 2400000,
        bonus: 300000,
        stock: 500000,
        total_compensation: 3200000,
        confidence_score: 0.9,
      },
      {
        company: "swiggy",
        role: "Software Engineer",
        level: "L4",
        location: "Bangalore",
        experience_years: 3,
        base_salary: 2200000,
        bonus: 250000,
        stock: 450000,
        total_compensation: 2900000,
        confidence_score: 0.9,
      },
      {
        company: "zomato",
        role: "Software Engineer",
        level: "L4",
        location: "Gurgaon",
        experience_years: 3,
        base_salary: 2100000,
        bonus: 200000,
        stock: 400000,
        total_compensation: 2700000,
        confidence_score: 0.9,
      },
      {
        company: "razorpay",
        role: "Software Engineer",
        level: "L4",
        location: "Bangalore",
        experience_years: 3,
        base_salary: 2600000,
        bonus: 300000,
        stock: 600000,
        total_compensation: 3500000,
        confidence_score: 0.9,
      },
      {
        company: "atlassian",
        role: "Software Engineer",
        level: "L5",
        location: "Bangalore",
        experience_years: 6,
        base_salary: 4500000,
        bonus: 700000,
        stock: 1800000,
        total_compensation: 7000000,
        confidence_score: 0.9,
      },
    ],
  });
  console.log("Seeded successfully!");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
