// prisma/seed.js
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

function normalize(company) {
  return company.toLowerCase().trim();
}

const salaries = [
  // Google
  {
    company: "google",
    role: "Software Engineer",
    level: "L3",
    location: "Bangalore",
    experience_years: 1,
    base_salary: 2200000,
    bonus: 300000,
    stock: 500000,
  },
  {
    company: "google",
    role: "Software Engineer",
    level: "L4",
    location: "Bangalore",
    experience_years: 3,
    base_salary: 3500000,
    bonus: 600000,
    stock: 1200000,
  },
  {
    company: "google",
    role: "Software Engineer",
    level: "L5",
    location: "Bangalore",
    experience_years: 6,
    base_salary: 5000000,
    bonus: 1000000,
    stock: 2500000,
  },
  {
    company: "google",
    role: "Software Engineer",
    level: "L6",
    location: "Bangalore",
    experience_years: 10,
    base_salary: 7000000,
    bonus: 1500000,
    stock: 4000000,
  },
  {
    company: "google",
    role: "Data Scientist",
    level: "L4",
    location: "Hyderabad",
    experience_years: 4,
    base_salary: 3200000,
    bonus: 500000,
    stock: 1000000,
  },
  {
    company: "google",
    role: "Product Manager",
    level: "L5",
    location: "Bangalore",
    experience_years: 7,
    base_salary: 5500000,
    bonus: 1200000,
    stock: 2800000,
  },

  // Microsoft
  {
    company: "microsoft",
    role: "Software Engineer",
    level: "L3",
    location: "Hyderabad",
    experience_years: 1,
    base_salary: 1800000,
    bonus: 200000,
    stock: 400000,
  },
  {
    company: "microsoft",
    role: "Software Engineer",
    level: "L4",
    location: "Hyderabad",
    experience_years: 3,
    base_salary: 2800000,
    bonus: 400000,
    stock: 900000,
  },
  {
    company: "microsoft",
    role: "Software Engineer",
    level: "L5",
    location: "Hyderabad",
    experience_years: 6,
    base_salary: 4200000,
    bonus: 800000,
    stock: 2000000,
  },
  {
    company: "microsoft",
    role: "Software Engineer",
    level: "L6",
    location: "Hyderabad",
    experience_years: 9,
    base_salary: 5800000,
    bonus: 1200000,
    stock: 3200000,
  },
  {
    company: "microsoft",
    role: "Data Scientist",
    level: "L4",
    location: "Bangalore",
    experience_years: 4,
    base_salary: 2600000,
    bonus: 350000,
    stock: 800000,
  },

  // Amazon
  {
    company: "amazon",
    role: "Software Engineer",
    level: "L4",
    location: "Bangalore",
    experience_years: 2,
    base_salary: 2400000,
    bonus: 150000,
    stock: 1500000,
  },
  {
    company: "amazon",
    role: "Software Engineer",
    level: "L5",
    location: "Bangalore",
    experience_years: 5,
    base_salary: 3600000,
    bonus: 200000,
    stock: 2800000,
  },
  {
    company: "amazon",
    role: "Software Engineer",
    level: "L6",
    location: "Bangalore",
    experience_years: 8,
    base_salary: 5200000,
    bonus: 300000,
    stock: 4500000,
  },
  {
    company: "amazon",
    role: "Product Manager",
    level: "L5",
    location: "Bangalore",
    experience_years: 6,
    base_salary: 4000000,
    bonus: 250000,
    stock: 3000000,
  },

  // Meta
  {
    company: "meta",
    role: "Software Engineer",
    level: "L3",
    location: "Bangalore",
    experience_years: 1,
    base_salary: 2500000,
    bonus: 400000,
    stock: 800000,
  },
  {
    company: "meta",
    role: "Software Engineer",
    level: "L4",
    location: "Bangalore",
    experience_years: 3,
    base_salary: 3800000,
    bonus: 700000,
    stock: 1800000,
  },
  {
    company: "meta",
    role: "Software Engineer",
    level: "L5",
    location: "Bangalore",
    experience_years: 6,
    base_salary: 5500000,
    bonus: 1100000,
    stock: 3500000,
  },
  {
    company: "meta",
    role: "Data Scientist",
    level: "L5",
    location: "Bangalore",
    experience_years: 5,
    base_salary: 5000000,
    bonus: 900000,
    stock: 3000000,
  },

  // Flipkart
  {
    company: "flipkart",
    role: "Software Engineer",
    level: "L3",
    location: "Bangalore",
    experience_years: 1,
    base_salary: 1600000,
    bonus: 150000,
    stock: 200000,
  },
  {
    company: "flipkart",
    role: "Software Engineer",
    level: "L4",
    location: "Bangalore",
    experience_years: 3,
    base_salary: 2400000,
    bonus: 300000,
    stock: 500000,
  },
  {
    company: "flipkart",
    role: "Software Engineer",
    level: "L5",
    location: "Bangalore",
    experience_years: 6,
    base_salary: 3500000,
    bonus: 500000,
    stock: 900000,
  },
  {
    company: "flipkart",
    role: "Product Manager",
    level: "L4",
    location: "Bangalore",
    experience_years: 4,
    base_salary: 2800000,
    bonus: 400000,
    stock: 600000,
  },

  // Swiggy
  {
    company: "swiggy",
    role: "Software Engineer",
    level: "L3",
    location: "Bangalore",
    experience_years: 1,
    base_salary: 1500000,
    bonus: 120000,
    stock: 180000,
  },
  {
    company: "swiggy",
    role: "Software Engineer",
    level: "L4",
    location: "Bangalore",
    experience_years: 3,
    base_salary: 2200000,
    bonus: 250000,
    stock: 450000,
  },
  {
    company: "swiggy",
    role: "Software Engineer",
    level: "L5",
    location: "Bangalore",
    experience_years: 6,
    base_salary: 3200000,
    bonus: 400000,
    stock: 800000,
  },

  // Zomato
  {
    company: "zomato",
    role: "Software Engineer",
    level: "L3",
    location: "Gurgaon",
    experience_years: 1,
    base_salary: 1400000,
    bonus: 100000,
    stock: 150000,
  },
  {
    company: "zomato",
    role: "Software Engineer",
    level: "L4",
    location: "Gurgaon",
    experience_years: 3,
    base_salary: 2100000,
    bonus: 200000,
    stock: 400000,
  },
  {
    company: "zomato",
    role: "Data Scientist",
    level: "L4",
    location: "Gurgaon",
    experience_years: 4,
    base_salary: 2300000,
    bonus: 250000,
    stock: 500000,
  },

  // Razorpay
  {
    company: "razorpay",
    role: "Software Engineer",
    level: "L3",
    location: "Bangalore",
    experience_years: 1,
    base_salary: 1700000,
    bonus: 150000,
    stock: 250000,
  },
  {
    company: "razorpay",
    role: "Software Engineer",
    level: "L4",
    location: "Bangalore",
    experience_years: 3,
    base_salary: 2600000,
    bonus: 300000,
    stock: 600000,
  },
  {
    company: "razorpay",
    role: "Software Engineer",
    level: "L5",
    location: "Bangalore",
    experience_years: 6,
    base_salary: 3800000,
    bonus: 500000,
    stock: 1100000,
  },

  // Atlassian
  {
    company: "atlassian",
    role: "Software Engineer",
    level: "L4",
    location: "Bangalore",
    experience_years: 3,
    base_salary: 3000000,
    bonus: 400000,
    stock: 800000,
  },
  {
    company: "atlassian",
    role: "Software Engineer",
    level: "L5",
    location: "Bangalore",
    experience_years: 6,
    base_salary: 4500000,
    bonus: 700000,
    stock: 1800000,
  },
  {
    company: "atlassian",
    role: "Software Engineer",
    level: "L6",
    location: "Bangalore",
    experience_years: 9,
    base_salary: 6000000,
    bonus: 1000000,
    stock: 3000000,
  },

  // Adobe
  {
    company: "adobe",
    role: "Software Engineer",
    level: "L3",
    location: "Bangalore",
    experience_years: 1,
    base_salary: 1900000,
    bonus: 180000,
    stock: 350000,
  },
  {
    company: "adobe",
    role: "Software Engineer",
    level: "L4",
    location: "Bangalore",
    experience_years: 3,
    base_salary: 2900000,
    bonus: 350000,
    stock: 750000,
  },
  {
    company: "adobe",
    role: "Software Engineer",
    level: "L5",
    location: "Noida",
    experience_years: 6,
    base_salary: 4200000,
    bonus: 600000,
    stock: 1500000,
  },

  // Uber
  {
    company: "uber",
    role: "Software Engineer",
    level: "L4",
    location: "Bangalore",
    experience_years: 2,
    base_salary: 2700000,
    bonus: 350000,
    stock: 900000,
  },
  {
    company: "uber",
    role: "Software Engineer",
    level: "L5",
    location: "Bangalore",
    experience_years: 5,
    base_salary: 4000000,
    bonus: 600000,
    stock: 2000000,
  },
  {
    company: "uber",
    role: "Data Scientist",
    level: "L4",
    location: "Bangalore",
    experience_years: 4,
    base_salary: 2900000,
    bonus: 400000,
    stock: 900000,
  },
];

async function main() {
  console.log("Seeding database...");

  // Clear existing
  await prisma.salary.deleteMany();

  for (const s of salaries) {
    const total = s.base_salary + (s.bonus || 0) + (s.stock || 0);
    await prisma.salary.create({
      data: {
        company: normalize(s.company),
        role: s.role,
        level: s.level,
        location: s.location,
        experience_years: s.experience_years,
        base_salary: s.base_salary,
        bonus: s.bonus || 0,
        stock: s.stock || 0,
        total_compensation: total,
        confidence_score: 0.85,
      },
    });
  }

  console.log(`✅ Seeded ${salaries.length} salary entries`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
